version: '3'

services:
  todotests:
    build: ./todo-app/tests
    environment:
      - FRONT_HOST=localhost
      - FRONT_PORT=3000
  todofront:
    build: ./todo-app/front-end
    environment:
      - REACT_APP_API_HOST=localhost
      - REACT_APP_API_PORT=3001
    depends_on:
      - "todoback"
    restart: always
    ports:
        - 3000:3000
  todoback:
    build: ./todo-app/back-end/
    ports:
      - 3001:3001